# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=100, unique=True)),
                ('path1', models.CharField(max_length=100)),
                ('path2', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('active', models.CharField(max_length=100)),
                ('shipment', models.CharField(max_length=100)),
                ('menoy', models.CharField(max_length=100)),
                ('oldmenoy', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('choosecolor', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('imgt', models.CharField(max_length=100)),
                ('smallimg', models.CharField(max_length=100)),
                ('aveimg', models.CharField(max_length=100)),
                ('bigimg', models.CharField(max_length=100)),
                ('goodsintroduce', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('otherbarnd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goucar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('goodsinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Goodsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField()),
                ('bg_img', models.CharField(max_length=100)),
                ('htwo', models.CharField(max_length=100)),
                ('spano', models.CharField(max_length=100)),
                ('menoy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=80, unique=True)),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='goucar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
    ]
