# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=100, unique=True)),
                ('path1', models.CharField(max_length=100)),
                ('path2', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('active', models.CharField(max_length=100)),
                ('shipment', models.CharField(max_length=100)),
                ('menoy', models.CharField(max_length=100)),
                ('oldmenoy', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('choosecolor', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('imgt', models.CharField(max_length=100)),
                ('sall', models.CharField(max_length=100)),
                ('smallimg', models.CharField(max_length=100)),
                ('aveimg', models.CharField(max_length=100)),
                ('bigimg', models.CharField(max_length=100)),
                ('goodsintroduce', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('otherbarnd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField()),
                ('bg_img', models.CharField(max_length=100)),
                ('htwo', models.CharField(max_length=100)),
                ('spano', models.CharField(max_length=100)),
                ('menoy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=80, unique=True)),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
    ]
