# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.IntegerField()),
                ('path1', models.CharField(max_length=100)),
                ('path2', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('active', models.CharField(max_length=100)),
                ('shipment', models.CharField(max_length=100)),
                ('menoy', models.IntegerField()),
                ('oldmenoy', models.IntegerField()),
                ('standard', models.CharField(max_length=100)),
                ('choosecolor', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('imgt', models.CharField(max_length=100)),
                ('sall', models.CharField(max_length=100)),
                ('smallimg', models.CharField(max_length=100)),
                ('aveimg', models.CharField(max_length=100)),
                ('bigimg', models.CharField(max_length=100)),
                ('goodsintroduce', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('otherbarnd', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='special',
            name='menoy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='special',
            name='part',
            field=models.IntegerField(),
        ),
    ]
