# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181103_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goodsid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='menoy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='oldmenoy',
            field=models.CharField(max_length=100),
        ),
    ]
