# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goucar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('goodsinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Goodsinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
        ),
    ]
