# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181103_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goodsid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
