# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_lunbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField(max_length=10)),
                ('bg_img', models.CharField(max_length=100)),
                ('htwo', models.CharField(max_length=100)),
                ('spano', models.CharField(max_length=100)),
                ('menoy', models.IntegerField(max_length=10)),
            ],
        ),
    ]
